---
ID: "d1273a8a-9750-4461-a5cc-ba82b2482615"
Parent: "c1d41cbf-9d67-4993-a10f-de6a035b5f5d"
Template: "c1d41cbf-9d67-4993-a10f-de6a035b5f5d"
Path: /sitecore/templates/Project/AcademyMvc/Content/Abouts/About Mvc/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250205T120038Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "708d32a6-83ba-44ee-ab3d-bbf41f74e831"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250212T182327Z
