---
ID: "05a48573-00be-4e14-bbbc-2c5873e14029"
Parent: "1f130e08-646c-43a7-b75c-78d5d775da0e"
Template: "1f130e08-646c-43a7-b75c-78d5d775da0e"
Path: /sitecore/templates/Project/AcademyJss/Content Types/Banners/BannerJss/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250209T151714Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "999c40f8-aa42-486a-b248-f27beaae4dcd"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250219T095723Z
