---
ID: "7e269fa6-db86-43cc-8fbb-9fefcffef1e1"
Parent: "9ebcedf0-fdef-45dc-a274-2f01e95ff644"
Template: "9ebcedf0-fdef-45dc-a274-2f01e95ff644"
Path: /sitecore/templates/Project/AcademyJss/Navigations/Footers/Footer Link Jss/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250301T103617Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4a2485c2-1dab-4d28-a938-915c4c996e0a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250301T103617Z
